[package]
name = "mt-logic"
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = ["Gear Technologies"]

[dependencies]
gstd = { git = "https://github.com/gear-tech/gear.git", branch = "testnet" }
mt-logic-io = { path = "io" }
mt-storage-io = { path = "../mt-storage/io" }
primitive-types = { version = "0.12.1", default-features = false, features = ["scale-info"] }
hex = { version = "0.4.3", default-features = false, features = ["alloc"] }
hashbrown = "0.13.2"

[dev-dependencies]
gstd = { git = "https://github.com/gear-tech/gear.git", branch = "testnet", features = ["debug"] }
gtest = { git = "https://github.com/gear-tech/gear.git", branch = "testnet" }
tokio = "1"

[build-dependencies]
mt-logic-io = { path = "io" }
gear-wasm-builder = { git = "https://github.com/gear-tech/gear.git", branch = "testnet" }