[package]
name = "mt-main"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
gstd.workspace = true
mt-logic-io.workspace = true
mt-main-io.workspace = true
primitive-types.workspace = true
sp-core-hashing.workspace = true
hashbrown.workspace = true

[build-dependencies]
gmeta.workspace = true
mt-main-io.workspace = true
gear-wasm-builder.workspace = true

[dev-dependencies]
gstd = { workspace = true, features = ["debug"] }
gtest.workspace = true
gclient.workspace = true
blake2-rfc.workspace = true
subxt.workspace = true
tokio.workspace = true

[features]
# Used for inserting constants with WASM binaries (NOT paths) of the contract in
# the root crate. Usually these constants used in gclient tests instead of
# strings with paths to the binaries in the "target" directory. If you don't
# like this approach or don't use gclient tests, you can freely remove this
# feature from here and from the rest of the code.
binary-vendor = []
